---
title: "About Me"
description: |
  Here are some additional details about myself!
---
**Interests:** I love adventures in nature and exploring new places. During my free time you'll find me hiking a mountain, biking along the coast, kayaking in creeks or over waves, or practicing yoga on the beach. I enjoy birding and observing wildlife. Wetlands are my favorite ecosystem! I love all creatures, from tiny hairy spiders to ferocious mega fauna. I am partial to cats, but I like dogs as well of course! I also love socializing, meeting knew people, and learning about new things!

**Experience:** I graduated with my Bachelor's degree in Biology & Ecology from Towson University in 2017. After graduated I embarked on a three-month solo trip around the world to explore 8 countries on 3 different continents. While abroad I volunteered at a wildlife game reserve in South Africa and an elephant sanctuary in Thailand. From 2016 to 2020, I worked for Baltimore County Department of Recreation and Parks as a Park Naturalist. As a Park Naturalist, I taught the public about nature, wildlife, and environmental concerns. I also worked as an Environmental Educator for an environmental education non-profit at the northern tip of the Chesapeake Bay for a year between my undergraduate and graduate schooling. 

**Projects:** I am currently working on the graduate group capstone project *Combining Conservation & Community Empowerment: Establishing Community Forests in DRC*. We conducted connectivity, socioeconomic, and climate projection analyses to recommend best conservation and community development planning and management actions for community forest success. For more information on this project please see the "Master's Project" tab!


